### ISSUE TITLE
Its not that simple

### ISSUE THREAD

**Issue by EsoCoding** [benckx/are-rappers-gemini#1]
I agree critical thinking is important, but Astrology is not that simple as you assume here. No one is just a gemini or cancer or leo or whatever. If you dont understand Astrology, you won't understand how to test it either. Which by the way is almost impossible to do, since a horoscope has many layers and include all the planet up till pluto and some other points like chiron. Also planets make aspects with each other, which brings a really complex dynamic along with it. Which is kind of art to interpretate, let alone use scientific methods to test the interpretation. So its a lot more complex then you even can begin to realize and never are just a gemini. Because all the other planets are in different signs to. So if you have all other planets in aries and only have the sun in Gemini. Then you would according to the Astrological theory, behave more like a Aries then a Gemini. If all planets are spread across the horoscope, the signs that the planets are in and eh houses give you a idea how you do certain things. Besides that all the planets correspond to subjects, it also has language that based on archetypes and even has sort of a alphabet. And for all the theories, that debunk Astrology because Astronomically it's in incorrect, to bad for them. Because planets actual planets them selfs don't seem to play a rol. They are only the hands off a clock clock that in case of Pluto 2, telling what time it is.

In this case, a rapper writes lyrics,. And Lyrics are subject, belonging the planet Mercurius. Mercurius has everything to do with language, logic, perception, interpretation, communication. If Mercurius had been in Aries, it would result in someone who tells story's in enthousiastic ways, a pioneer, have lots of new idea's, initiates new idea's. When its in taurus, someone would take a long time making a choice. This is because it wants to commit to it and does not like changing its mind, cares about materialistic things, so thinking about money and how to get it will keep them bussy.  If its in gemini, you find the persons who often are very social, know all the neighbord, or follow the latest news. If a rapper would have mercurius in gemini, it would surely be a create one who could easily do some freestyles. If it was in the taurus sign, then doing some freestyle is a lot more complex. But even if its in gemini, but its making a conjunction with planet saturn. The freestyle could be harder. And so does each sign tell something about the thinking process and how it reacts, responds, talk, analyzes, observe, communicate. But a rapper is not only one who writes lyrics, it is also a Artist, so a rapper might also have some planets in that sign, which is the sign that wants to be seen, have the looks, and  wants be acknowledged and impress others. You also probably need to be a good at other thiings to. I mean being a real rapper that performances on big stage, you also need to run a company, need to be able to plan and o things. Which also correspond to parts of a horoscope. 

So critical thinking also mean you research the subject, and do not assume anything before fact checking. This script you made for fun, ovisoulsy. But it will indeed say nothing. I'm trying to do the same as you, but i am already researching Astrology for long time. And i can't proof it, but also not debunk it.

**Comment by benckx** [comment]
She told me "most rapper are Gemini". I showed this was not true.

**Comment by EsoCoding** [comment]
She likely meant to say that Gemini is associated with language and communication. A good rap lyric exemplifies creative use of language. Among the three air signs, which all place importance on language, Gemini may play a crucial role in the horoscope of a rapper.

However, upon examining the percentages, I am still surprised. You might have unwittingly uncovered a coincidence that even I wouldn't have anticipated. If I were to identify a sign common among rappers, I would choose Leo. This is because famous and well-known musical artists often have more in common with the sign of Leo. As the quintessential show business personality, Leo craves attention, relishes in glitter and glamour, and knows how to impress others. Leos have a knack for selling themselves to the public and even profiting from it. Interestingly, Leo has the highest percentage among the signs, at least more than the others.

Another coincidence is that Aquarius has the lowest percentage. Aquarius is the sign opposite Leo in the zodiac, and in astrology, opposite signs often exhibit contrasting traits. For example, Aries is unbalanced, Libra is balanced, Taurus is careful, and Scorpio is extreme. Aquarius, unlike Leo, does not enjoy attention and is often seen as the oddball or the outcast. It embraces unique and unpopular opinions. It is intriguing to observe how the percentages of these two signs differ significantly from each other.
